#!/bin/bash

#the variables
#im using alsa because reasons
#VOLUME_STATE=$(amixer sget Master | grep -wo -m 1 "on\|off")
#VOLUME_PERCENT=$(amixer sget Master | grep -o -m 1 '[0-9]\+%' | tr -d '%')
USB_LABEL=$(lsblk -e 259 -o KNAME -n | grep -n 1 | tr -d '2:')

#echo "$USB_LABEL"

if [[ ! -z "$USB_LABEL" ]]; then
#	echo "$USB_LABEL"
        udisksctl mount -b /dev/"${USB_LABEL}"; 
#	echo "${USB_LABEL} mounted."
fi

# volume percentage convert into the icons
# also the % can go above 100% so DBZ meme nessesitated
#if [[ "${VOLUME_PERCENT}" -ge "9000" ]]; then
#	VOLUME_IND="!!OVER 9000!!"
#elif [[ "${VOLUME_PERCENT}" -ge "50" ]]; then 
#	VOLUME_IND=""
#elif [[ "${VOLUME_PERCENT}" -ge "20" ]]; then 
#	VOLUME_IND=""
#elif [[ "${VOLUME_PERCENT}" -ge "0" ]]; then 
#	VOLUME_IND="" 
#fi


# volume mute indicator
#if [[ "${VOLUME_STATE}" = "off" ]]; then
#	VOLUME_IND=""
#fi


# the print command
#echo "<span size ='large'>${VOLUME_IND}</span> ${VOLUME_PERCENT}"



