# mbsync
# Autogenerated from man page /usr/share/man/man1/mbsync.1.gz
complete -c mbsync -s c -l config --description 'Read configuration from file.  By default, the configuration is read from ~/.'
complete -c mbsync -s a -l all --description 'Select all configured channels.'
complete -c mbsync -s l -l list --description 'Don\'t synchronize anything, but list all mailboxes in the selected channels a…'
complete -c mbsync -s C -l 'create[-master' -o slave --description 'Override any Create options from the config file.  See below.'
complete -c mbsync -s R -l 'remove[-master' --description 'Override any Remove options from the config file.  See below.'
complete -c mbsync -s X -l 'expunge[-master' --description 'Override any Expunge options from the config file.  See below.'
complete -c mbsync -s n -s N -s d -s f -s 0 -s F --description '{--new|--renew|--delete|--flags|--noop|--full}.'
complete -c mbsync -s H --description '{--pull|--push}[-new|-renew|-delete|-flags] Override any Sync options from th…'
complete -c mbsync -s h -l help --description 'Display a summary of command line options.'
complete -c mbsync -s v -l version --description 'Display version information.'
complete -c mbsync -s V -l verbose --description 'Enable verbose mode, which displays what is currently happening.'
complete -c mbsync -o 'D[d' --description '--debug[-crash|-driver|-driver-all|-maildir|-main|-net|-net-all|-sync] Enable…'
complete -c mbsync -s q -l quiet --description 'Suppress progress counters (this is implicit if stdout is no TTY, or any debu…'

