# mdconvert
# Autogenerated from man page /usr/share/man/man1/mdconvert.1.gz
complete -c mdconvert -s a -l alt --description 'Convert to the alternative (Berkeley DB based) UID storage scheme.'
complete -c mdconvert -s n -l native --description 'Convert to the native (file name based) UID storage scheme.'
complete -c mdconvert -s h -l help --description 'Displays a summary of command line options.'
complete -c mdconvert -s v -l version --description 'Displays version information.'

