# msmtpd
# Autogenerated from man page /usr/share/man/man1/msmtpd.1.gz
complete -c msmtpd -l version --description 'Print version information.'
complete -c msmtpd -l help --description 'Print help.'
complete -c msmtpd -l inetd --description 'Start single SMTP session on stdin/stdout.'
complete -c msmtpd -l interface --description 'Listen on the given IPv6 or IPv4 address instead of 127. 0. 0. 1.'
complete -c msmtpd -l port --description 'Listen on the given port number instead of 25.'
complete -c msmtpd -l command --description 'Pipe mails to cmd instead of msmtp EXAMPLES.'

